// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Server.Data;

#nullable disable

namespace TechStore.Server.Migrations
{
    [DbContext(typeof(TechStoreDbContext))]
    [Migration("20230104180115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Server.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TechStore.Server.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TechStore.Server.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "ATX Mid / Black / Steel / Plastic / Tempered Glass.",
                            ImageURL = "",
                            Name = "Corsair 4000D Airflow Computer Case",
                            Price = 104.99m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "ATX Mid / White / Steel / Plastic / Tempered Glass.",
                            ImageURL = "",
                            Name = "Corsair iCUE 5000X RGB Computer Case",
                            Price = 204.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "ATX Mid / Black / Steel / Tempered Glass.",
                            ImageURL = "",
                            Name = "Phanteks Eclipse G360A Computer Case",
                            Price = 99.99m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "ATX Mid / Aluminum / Steel.",
                            ImageURL = "",
                            Name = "LIAN LI 011 Dynamic EVO Computer Case",
                            Price = 175.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "MicroATX / White / Steel / Tempered Glass.",
                            ImageURL = "",
                            Name = "Thermaltake S100 TG Snow Computer Case",
                            Price = 67.99m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "8-Core / 3.4 GHz / DDR4 3200 / 105W.",
                            ImageURL = "",
                            Name = "AMD Ryzen 7 5800X3D Desktop Processor",
                            Price = 356.99m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "12-Core (8P+4E) / 3.6 GHz / DDR5 4800 / 125W.",
                            ImageURL = "",
                            Name = "Intel Core i7-12700K Desktop Processor",
                            Price = 323.99m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "8-Core / 3.4 GHz / DDR4 3200 / 65W",
                            ImageURL = "",
                            Name = "AMD Ryzen 7 5700X Desktop Processor",
                            Price = 196.99m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "24-Core (8P+16E) / 2.2 GHz / DDR5 5600 / 125W.",
                            ImageURL = "",
                            Name = "Intel Core i9-13900K Desktop Processor",
                            Price = 609.99m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "16-Core / 3.4 GHz / DDR4 3200 / 105W.",
                            ImageURL = "",
                            Name = "AMD Ryzen 9 5950X Desktop Processor",
                            Price = 543.99m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "12-Core / 3.7 GHz / DDR4 3200 / 105W.",
                            ImageURL = "",
                            Name = "AMD Ryzen 9 5900X Desktop Processor",
                            Price = 347.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "AM4 / ATX / 128GB / 4x288pin (DDR4) / AMD B550.",
                            ImageURL = "",
                            Name = "Asus Strix B550-F Wi-Fi Motherboard",
                            Price = 204.99m,
                            Qty = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "AM5 / ATX / 128GB / 4x288pin (DDR5) / AMD B650.",
                            ImageURL = "",
                            Name = "Gigabyte B650 Aorus Elite AX Motherboard",
                            Price = 229.99m,
                            Qty = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "LGA 1200 / ATX / 128GB / 4x288pin (DDR4) / Intel Z490.",
                            ImageURL = "",
                            Name = "MSI Mag Z490 Tomahawk ATX Motherboard",
                            Price = 122.99m,
                            Qty = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "LGA 1700 / ATX / 128GB / 4x288pin (DDR5) / Intel Z790",
                            ImageURL = "",
                            Name = "Asus ROG Strix Z790-E Wi-Fi Motherboard",
                            Price = 499.99m,
                            Qty = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "LGA 1700 / ATX / 128GB / 4x288pin (DDR4) / Intel Z790.",
                            ImageURL = "",
                            Name = "MSI Pro Z790-P Wi-Fi Motherboard",
                            Price = 239.99m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "AM5 / ATX / 128GB / 4x288pin (DDR5) / AMD X670E.",
                            ImageURL = "",
                            Name = "Asus Crosshair X670E Hero Wi-Fi Motherboard",
                            Price = 699.99m,
                            Qty = 73
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "DDR4 / 16GB (2 x 8GB) / Black / 18.",
                            ImageURL = "",
                            Name = "G.Skill Trident Z RGB Memory",
                            Price = 70.99m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "DDR5 / 32GB (2 x 16GB) / Black / 32.",
                            ImageURL = "",
                            Name = "G.Skill Trident Z5 RGB Memory",
                            Price = 199.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "DDR4 / 32GB (2 x 16GB) / Black / 16.",
                            ImageURL = "",
                            Name = "Corsair Vengeance RGB Pro SL Memory",
                            Price = 106.99m,
                            Qty = 70
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "DDR5 / 16GB (2 x 8GB) / Platinum / 36.",
                            ImageURL = "",
                            Name = "OLOy Blade RGB Memory",
                            Price = 94.99m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "DDR4 / 64GB (2 x 32GB) / Black / 16.",
                            ImageURL = "",
                            Name = "Corsair Vengeance LPX Memory",
                            Price = 184.99m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "DDR5 / 32GB (2 x 16GB) / Black / 36.",
                            ImageURL = "",
                            Name = "G.Skill Trident Z5 RGB Memory",
                            Price = 374.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            Description = "GeForce RTX 3060 / 12GB / 1807 MHz / PCI Express 4.0.",
                            ImageURL = "",
                            Name = "MSI RTX 3060 Ventus 2X GPU",
                            Price = 369.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "GeForce RTX 3080 / 10GB / 1440 MHz / PCI Express 4.0.",
                            ImageURL = "",
                            Name = "Peladn Gaming RTX 3080 RGB GPU",
                            Price = 699.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "Radeon RX 6700 XT / 12GB / 2620 MHz / PCI Express 4.0.",
                            ImageURL = "",
                            Name = "MSI RX 6700 XT Mech 2X GPU",
                            Price = 369.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "GeForce RTX 4080 / 16GB / 2625 MHz / PCI Express 4.0.",
                            ImageURL = "",
                            Name = "Asus ROG Strix RTX 4080 GPU",
                            Price = 1675.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Description = "ATX12V/EPS12V / 80 Plus Gold Certified / 750W / Full Modular.",
                            ImageURL = "",
                            Name = "Corsair RMx Series RM750 Power Supply",
                            Price = 114.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            Description = "ATX12V/EPS12V / 80 Plus Gold Cerified / 500W / Non Modular.",
                            ImageURL = "",
                            Name = "Thermaltake Smart 500W Power Supply",
                            Price = 39.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Description = "ATX12V/EPS12V / 80 Plus Gold Certified / 1000W / Full Modular.",
                            ImageURL = "",
                            Name = "SeaSonic Prime Ultra Titanium Power Supply",
                            Price = 328.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            Description = "ATX12V/EPS12V / 80 Plus Gold Certified / 1300W / Full Modular.",
                            ImageURL = "",
                            Name = "EVGA SuperNova 1300 G+ Power Supply",
                            Price = 225.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            Description = ".",
                            ImageURL = "4TB / 5400 RPM / 256MB / 3.5 / SATA 6.0Gb/s",
                            Name = "Seagate Hard Drives ST4000DM004 Storage",
                            Price = 67.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            Description = "12TB / 7200 RPM / 256MB / 3.5 / SATA 6.0Gb/s.",
                            ImageURL = "",
                            Name = "Seagate IronWolf ST12000VN0008 Storage",
                            Price = 199.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            Description = "1TB / 1024MB / M.2 2280 / PCI Express 4.0 x4.",
                            ImageURL = "",
                            Name = "Samsung 980 PRO MZ-V8P1T0B/AM Storage",
                            Price = 129.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            Description = "1TB / M.2 2280 / PCI Express 3.0 x4.",
                            ImageURL = "",
                            Name = "Seagate BarraCuda Q5 ZP1000CV3A001 Storage",
                            Price = 130.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            Description = "Variable / Variable / Black.",
                            ImageURL = "",
                            Name = "Cooler Master RR-2V2E-18PK-R2 CPU Cooler",
                            Price = 54.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            Description = "Variable / 25-30 dBA / Black.",
                            ImageURL = "",
                            Name = "Deepcool AK620 CPU Cooler",
                            Price = 64.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 8,
                            Description = "Variable / 10-36 dBA / Black / RGB.",
                            ImageURL = "",
                            Name = "Corsair CW-9060047-WW CPU Water Cooler",
                            Price = 169.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 8,
                            Description = "Variable / 31-36 dBA / Black / RGB.",
                            ImageURL = "",
                            Name = "NZXT RL-KRX53-01 CPU Water Cooler",
                            Price = 134.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 9,
                            Description = "Home / 64-bit.",
                            ImageURL = "",
                            Name = "Microsoft Windows 11 Home 64-bit, DVD",
                            Price = 119.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            Description = "Pro / 64-bit.",
                            ImageURL = "",
                            Name = "Windows 11 Pro 64-bit, USB",
                            Price = 199.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 9,
                            Description = "Home / 64-bit.",
                            ImageURL = "",
                            Name = "Windows 10 Home 64-bit, DVD",
                            Price = 374.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 9,
                            Description = "Professional / 32-bit.",
                            ImageURL = "",
                            Name = "Windows 10 Pro 32-bit, OEM",
                            Price = 159.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 10,
                            Description = "Chroma RGB / 11 Programable Buttons / Black.",
                            ImageURL = "",
                            Name = "Razer Basilisk V3 Pro Wireless Mouse",
                            Price = 159.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 10,
                            Description = "Wired / Red.",
                            ImageURL = "",
                            Name = "HyperX Alloy MKW100 Mechanical Keyboard",
                            Price = 79.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 10,
                            Description = "31.5 / 165 Hz / 5ms / VA.",
                            ImageURL = "",
                            Name = "LG 32in 32GN50R-B UltraGear Full HD 1080p",
                            Price = 248.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 10,
                            Description = "USB / Black / 30fps.",
                            ImageURL = "",
                            Name = "Logitech C920x HD Pro Webcam Full HD 1080p",
                            Price = 69.99m,
                            Qty = 150
                        });
                });

            modelBuilder.Entity("TechStore.Server.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Case"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Motherboard"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Memory"
                        },
                        new
                        {
                            Id = 5,
                            Name = "VideoCards"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PowerSupply"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CPUCooler"
                        },
                        new
                        {
                            Id = 9,
                            Name = "OperatingSystem"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("TechStore.Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Matthew"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sutter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
